### ISSUE TITLE
START_GAME react warning

### ISSUE THREAD

**Issue by cristiean** [eniallator/Property-Tycoon#28]
This shows in the console upon starting a new game. What is it?

<img width="782" alt="Screenshot 2020-04-07 at 23 40 21" src="https://user-images.githubusercontent.com/24500712/78726356-ab226700-7929-11ea-950f-0d28a7f0509a.png">

**Comment by Joe-Fin** [comment]
What a blast from the past

**Comment by cristiean** [comment]
So many mixed feelings
